# Generated by Django 4.1.4 on 2022-12-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActualBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('loans', models.DecimalField(decimal_places=2, max_digits=4)),
                ('groceries', models.DecimalField(decimal_places=2, max_digits=4)),
                ('leisure', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hygiene', models.DecimalField(decimal_places=2, max_digits=4)),
                ('haircut', models.DecimalField(decimal_places=2, max_digits=4)),
                ('carPayment', models.DecimalField(decimal_places=2, max_digits=4)),
                ('carInsurance', models.DecimalField(decimal_places=2, max_digits=4)),
                ('gas', models.DecimalField(decimal_places=2, max_digits=4)),
                ('phone', models.DecimalField(decimal_places=2, max_digits=4)),
                ('internet', models.DecimalField(decimal_places=2, max_digits=4)),
                ('utilities', models.DecimalField(decimal_places=2, max_digits=4)),
                ('savings', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='IdealBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('loans', models.DecimalField(decimal_places=2, max_digits=4)),
                ('groceries', models.DecimalField(decimal_places=2, max_digits=4)),
                ('leisure', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hygiene', models.DecimalField(decimal_places=2, max_digits=4)),
                ('haircut', models.DecimalField(decimal_places=2, max_digits=4)),
                ('carPayment', models.DecimalField(decimal_places=2, max_digits=4)),
                ('carInsurance', models.DecimalField(decimal_places=2, max_digits=4)),
                ('gas', models.DecimalField(decimal_places=2, max_digits=4)),
                ('phone', models.DecimalField(decimal_places=2, max_digits=4)),
                ('internet', models.DecimalField(decimal_places=2, max_digits=4)),
                ('utilities', models.DecimalField(decimal_places=2, max_digits=4)),
                ('savings', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
